### ISSUE TITLE
Docker run command

### ISSUE THREAD

**Issue by YaoTingYao** [HamedAlemo/stac-search-tutorial#2]
Hi @HamedAlemo,  just a small tweak. Since the Docker image name is ```hamedalemo/stac-search-tutorial:1.0```, the docker run command needs to be revised as follows. Cheers!
```
docker run -v /docker hamedalemo/stac-search-tutorial:1.0
```

**Comment by HamedAlemo** [comment]
Thanks YaoTing. I updated this in the latest commit ([9658c51](https://github.com/HamedAlemo/stac-search-tutorial/commit/9658c51a966aa26471ff7a7ff7c28c1179cc8ab7)).
